# Generated by Django 3.2.4 on 2021-07-22 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tweets',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='tweets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2021-06-15 15:05:15"),
            preserve_default=False,
        ),
    ]
